logging:
  level:
    root: WARN
    org.springframework: INFO
    org.apache.kafka: INFO

spring:
  application:
    name: async-to-sync
  kafka:
    bootstrap-servers: localhost:29092
    properties:
      schema-registry-url: http://localhost:8081
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer